# dataset_path: '/media/database/data2/Expression/BP4D/BP4D_MTCNN'
dataset_path_subject_independent: '/media/data1/wf/AU_EMOwPGM/codes/dataset/BP4D/BP4D_subject_independent.pkl'
dataset_path_subject_dependent: '/media/data1/wf/AU_EMOwPGM/codes/dataset/BP4D/BP4D_subject_dependent.pkl'
num_classes: 17
neighbor_num: 4