dataset_path_subject_independent: '/media/data1/wf/AU_EMOwPGM/codes/dataset/DISFA/DISFA_subject_independent.pkl'
dataset_path_subject_dependent: '/media/data1/wf/AU_EMOwPGM/codes/dataset/DISFA/DISFA_subject_dependent.pkl'
num_classes: 12
neighbor_num: 3
loc1: [0, 1, 2, 3, 4, 6, 9, 10, 11, 12, 15, 16]
loc2: [5, 7, 8, 13, 14]