dataset_path_subject_independent: '/media/data1/wf/AU_EMOwPGM/codes/dataset/RAF-DB/RAF_compound_subject_independent.pkl'
# num_classes: 12
# neighbor_num: 3
# loc1: [0, 1, 2, 3, 4, 6, 9, 10, 11, 12, 15, 16]
# loc2: [5, 7, 8, 13, 14]
num_classes: 17
neighbor_num: 4
loc1: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
loc2: [15, 16]